### ISSUE TITLE
Are you open to contributions / what is the licensing situation?

### ISSUE THREAD

**Issue by eddie-atkinson** [omidmt/pyvizpo#1]
First of all thank you for publishing this work

I was wondering if you were open to others making PRs on this repo with a few refinements? It doesn't look like this library would work out of the box with Python3. Are you amenable to me making them and then contributing them? Also small QoL improvements like adding a `requirements.txt` file would make this library much easier for others to pick up.

Obviously that raises the question of what license this repo is released under. Right now the lack of a license means that I couldn't legally contribute to or extend this code.

**Comment by omidmt** [comment]
Sure, license added.
